/**
 * ColorMill v2 — pigment palette and Mixbox latent helpers (pure TS, tested).
 *
 * A Mixbox latent is 7 floats { c0, c1, c2, c3, rR, rG, rB }: four
 * Kubelka-Munk pigment weights (c3 = 1 - c0 - c1 - c2) plus an sRGB residual.
 * Mixing is a mass-weighted average in latent space; decoding is
 * evalPolynomial(c0..c3) + residual, clamped to 0..1 (design §5).
 *
 * The palette constants between the BEGIN/END GENERATED markers are produced
 * by `node scripts/gen-pigments.mjs` from the official mixbox.js and must not
 * be edited by hand. `rgbToLatentAsync` lazy-loads that 176 KB library at
 * runtime for the custom colour picker only.
 *
 * Mixbox is (c) Secret Weapons, CC BY-NC 4.0 (non-commercial use).
 */
import type { Latent } from '../sim/types';

export type { Latent };

export interface Pigment {
  /** identifier used by the UI, keyboard shortcuts and window.__colormill.tapPigment */
  readonly key: string;
  readonly name: string;
  /** '#rrggbb' */
  readonly hex: string;
  /** sRGB 0..1 */
  readonly srgb: readonly [number, number, number];
  readonly latent: Latent;
}

// BEGIN GENERATED
// Generated by scripts/gen-pigments.mjs from web/vendor/mixbox/mixbox.js — do not edit by hand.
export const PIGMENTS: Readonly<Record<string, Pigment>> = {
  cadmiumYellow: { // #FEEC00
    key: 'cadmiumYellow', name: 'Cadmium Yellow', hex: '#feec00',
    srgb: [0.996078, 0.925490, 0.000000],
    latent: [0.00392157, 0.85914648, 0.00000000, 0.13693195, 0.03304325, 0.10291498, -0.08081249]
  },
  hansaYellow: { // #FCD300
    key: 'hansaYellow', name: 'Hansa Yellow', hex: '#fcd300',
    srgb: [0.988235, 0.827451, 0.000000],
    latent: [0.00392157, 0.93434127, 0.00392157, 0.05781559, 0.03336587, 0.02504378, -0.05726174]
  },
  cadmiumOrange: { // #FF6900
    key: 'cadmiumOrange', name: 'Cadmium Orange', hex: '#ff6900',
    srgb: [1.000000, 0.411765, 0.000000],
    latent: [0.01176471, 0.66551326, 0.31903114, 0.00369089, 0.03670441, 0.01032648, -0.16149285]
  },
  cadmiumRed: { // #FF2702
    key: 'cadmiumRed', name: 'Cadmium Red', hex: '#ff2702',
    srgb: [1.000000, 0.152941, 0.007843],
    latent: [0.00000000, 0.33954705, 0.65865581, 0.00179714, 0.08875297, -0.01751668, -0.06770563]
  },
  quinacridoneMagenta: { // #80022E
    key: 'quinacridoneMagenta', name: 'Quinacridone Magenta', hex: '#80022e',
    srgb: [0.501961, 0.007843, 0.180392],
    latent: [0.22938870, 0.00000000, 0.72073818, 0.04987313, 0.00317729, -0.10106154, 0.00060886]
  },
  cobaltViolet: { // #4E0042
    key: 'cobaltViolet', name: 'Cobalt Violet', hex: '#4e0042',
    srgb: [0.305882, 0.000000, 0.258824],
    latent: [0.42168397, 0.00392157, 0.55252595, 0.02186851, -0.00088666, -0.08927438, -0.01728965]
  },
  ultramarineBlue: { // #190059
    key: 'ultramarineBlue', name: 'Ultramarine Blue', hex: '#190059',
    srgb: [0.098039, 0.000000, 0.349020],
    latent: [0.84668973, 0.00926521, 0.14080738, 0.00323767, 0.00434762, -0.02400251, -0.01688435]
  },
  cobaltBlue: { // #002185
    key: 'cobaltBlue', name: 'Cobalt Blue', hex: '#002185',
    srgb: [0.000000, 0.129412, 0.521569],
    latent: [0.86445213, 0.00452134, 0.02953470, 0.10149182, -0.05364788, -0.01203575, 0.00345821]
  },
  phthaloBlue: { // #0D1B44
    key: 'phthaloBlue', name: 'Phthalo Blue', hex: '#0d1b44',
    srgb: [0.050980, 0.105882, 0.266667],
    latent: [0.90556027, 0.07484850, 0.00610039, 0.01349085, -0.00776365, 0.00368427, 0.00493401]
  },
  phthaloGreen: { // #003C32
    key: 'phthaloGreen', name: 'Phthalo Green', hex: '#003c32',
    srgb: [0.000000, 0.235294, 0.196078],
    latent: [0.70912545, 0.27821426, 0.01082841, 0.00183187, -0.02697068, 0.00263361, -0.01223470]
  },
  permanentGreen: { // #076D16
    key: 'permanentGreen', name: 'Permanent Green', hex: '#076d16',
    srgb: [0.027451, 0.427451, 0.086275],
    latent: [0.48032295, 0.51547866, 0.00412348, 0.00007490, -0.03705742, 0.02571728, -0.12413506]
  },
  sapGreen: { // #6B9404
    key: 'sapGreen', name: 'Sap Green', hex: '#6b9404',
    srgb: [0.419608, 0.580392, 0.015686],
    latent: [0.19606709, 0.77697809, 0.02768655, -0.00073172, -0.01365738, -0.01454314, -0.15701284]
  },
  burntSienna: { // #7B4800
    key: 'burntSienna', name: 'Burnt Sienna', hex: '#7b4800',
    srgb: [0.482353, 0.282353, 0.000000],
    latent: [0.23806174, 0.32752018, 0.43238754, 0.00203053, -0.02650550, 0.03609869, -0.13229236]
  },
  titaniumWhite: { // #FFFFFF
    key: 'titaniumWhite', name: 'Titanium White', hex: '#ffffff',
    srgb: [1.000000, 1.000000, 1.000000],
    latent: [0.00000000, 0.00000000, 0.00000000, 1.00000000, 0.00481862, 0.00021851, 0.00295198]
  },
  ivoryBlack: { // #000000
    key: 'ivoryBlack', name: 'Ivory Black', hex: '#000000',
    srgb: [0.000000, 0.000000, 0.000000],
    latent: [0.48627451, 0.26274510, 0.24705882, 0.00392157, -0.22201499, -0.22129656, -0.22017007]
  }
};
// END GENERATED

/** Fresh silicone base = Titanium White (design §5). */
export const BASE_LATENT: Latent = PIGMENTS.titaniumWhite.latent;

/**
 * Palette order for the bottom bar. The first eight are the design §5
 * pigments and map to keyboard shortcuts 1–8; the rest follow.
 */
export const PALETTE_ORDER: readonly string[] = [
  'cadmiumRed', 'cadmiumYellow', 'cobaltBlue', 'phthaloGreen', 'ultramarineBlue', 'burntSienna', 'ivoryBlack', 'titaniumWhite',
  'hansaYellow', 'cadmiumOrange', 'quinacridoneMagenta', 'cobaltViolet', 'phthaloBlue', 'permanentGreen', 'sapGreen'
];

/** Short names accepted by findPigment() in addition to the palette keys. */
export const PIGMENT_ALIASES: Readonly<Record<string, string>> = {
  white: 'titaniumWhite',
  black: 'ivoryBlack',
  red: 'cadmiumRed',
  yellow: 'cadmiumYellow',
  blue: 'cobaltBlue',
  green: 'phthaloGreen',
  ultramarine: 'ultramarineBlue',
  orange: 'cadmiumOrange',
  magenta: 'quinacridoneMagenta',
  violet: 'cobaltViolet',
  sienna: 'burntSienna'
};

/**
 * Look a pigment up by key, alias, display name or hex (case-insensitive,
 * ignoring spaces). Returns undefined when nothing matches.
 */
export function findPigment(name: string): Pigment | undefined {
  if (!name) return undefined;
  const direct = PIGMENTS[name];
  if (direct) return direct;
  const norm = name.toLowerCase().replace(/[\s_-]/g, '');
  const alias = PIGMENT_ALIASES[norm];
  if (alias) return PIGMENTS[alias];
  for (const p of Object.values(PIGMENTS)) {
    if (p.key.toLowerCase() === norm || p.name.toLowerCase().replace(/\s/g, '') === norm || p.hex === norm.replace(/^#?/, '#')) {
      return p;
    }
  }
  return undefined;
}

function clamp01(x: number): number {
  return x < 0 ? 0 : x > 1 ? 1 : x;
}

/**
 * Mixbox polynomial on the four pigment weights — a straight port of
 * `EvalPolynomial` in src/sim/mixbox.c (which mirrors mixbox.js). Returns
 * the unclamped RGB without the residual.
 */
export function evalPolynomial(c0: number, c1: number, c2: number, c3: number): [number, number, number] {
  const c00 = c0 * c0;
  const c11 = c1 * c1;
  const c22 = c2 * c2;
  const c33 = c3 * c3;
  const c01 = c0 * c1;
  const c02 = c0 * c2;
  const c12 = c1 * c2;

  let r = 0, g = 0, b = 0, w: number;
  w = c0 * c00; r += +0.07717053 * w; g += +0.02826978 * w; b += +0.24832992 * w;
  w = c1 * c11; r += +0.95912302 * w; g += +0.80256528 * w; b += +0.03561839 * w;
  w = c2 * c22; r += +0.74683774 * w; g += +0.04868586 * w; b += +0.00000000 * w;
  w = c3 * c33; r += +0.99518138 * w; g += +0.99978149 * w; b += +0.99704802 * w;
  w = c00 * c1; r += +0.04819146 * w; g += +0.83363781 * w; b += +0.32515377 * w;
  w = c01 * c1; r += -0.68146950 * w; g += +1.46107803 * w; b += +1.06980936 * w;
  w = c00 * c2; r += +0.27058419 * w; g += -0.15324870 * w; b += +1.98735057 * w;
  w = c02 * c2; r += +0.80478189 * w; g += +0.67093710 * w; b += +0.18424500 * w;
  w = c00 * c3; r += -0.35031003 * w; g += +1.37855826 * w; b += +3.68865000 * w;
  w = c0 * c33; r += +1.05128046 * w; g += +1.97815239 * w; b += +2.82989073 * w;
  w = c11 * c2; r += +3.21607125 * w; g += +0.81270228 * w; b += +1.03384539 * w;
  w = c1 * c22; r += +2.78893374 * w; g += +0.41565549 * w; b += -0.04487295 * w;
  w = c11 * c3; r += +3.02162577 * w; g += +2.55374103 * w; b += +0.32766114 * w;
  w = c1 * c33; r += +2.95124691 * w; g += +2.81201112 * w; b += +1.17578442 * w;
  w = c22 * c3; r += +2.82677043 * w; g += +0.79933038 * w; b += +1.81715262 * w;
  w = c2 * c33; r += +2.99691099 * w; g += +1.22593053 * w; b += +1.80653661 * w;
  w = c01 * c2; r += +1.87394106 * w; g += +2.05027182 * w; b += -0.29835996 * w;
  w = c01 * c3; r += +2.56609566 * w; g += +7.03428198 * w; b += +0.62575374 * w;
  w = c02 * c3; r += +4.08329484 * w; g += -1.40408358 * w; b += +2.14995522 * w;
  w = c12 * c3; r += +6.00078678 * w; g += +2.55552042 * w; b += +1.90739502 * w;
  return [r, g, b];
}

/** Decode a latent to sRGB 0..1 (polynomial + residual, clamped). */
export function latentToRgb(latent: ArrayLike<number>): [number, number, number] {
  const [r, g, b] = evalPolynomial(latent[0], latent[1], latent[2], latent[3]);
  return [clamp01(r + latent[4]), clamp01(g + latent[5]), clamp01(b + latent[6])];
}

/** Decode a latent straight to a CSS '#rrggbb' string. */
export function latentToHex(latent: ArrayLike<number>): string {
  return rgbToHex(latentToRgb(latent));
}

/**
 * Mass-weighted average of latents. Weights need not sum to one; entries
 * with non-positive weight are ignored. With no usable entries this returns
 * the base (white) latent.
 */
export function mixLatents(entries: ReadonlyArray<{ latent: ArrayLike<number>; weight: number }>): Latent {
  const acc = [0, 0, 0, 0, 0, 0, 0];
  let total = 0;
  for (const e of entries) {
    if (!(e.weight > 0)) continue;
    total += e.weight;
    for (let i = 0; i < 7; i++) acc[i] += e.weight * e.latent[i];
  }
  if (total <= 0) return BASE_LATENT;
  return [acc[0] / total, acc[1] / total, acc[2] / total, acc[3] / total, acc[4] / total, acc[5] / total, acc[6] / total];
}

/** Linear interpolation of two latents (t = 0 → a, t = 1 → b). */
export function lerpLatent(a: ArrayLike<number>, b: ArrayLike<number>, t: number): Latent {
  const out = [0, 0, 0, 0, 0, 0, 0];
  for (let i = 0; i < 7; i++) out[i] = a[i] + (b[i] - a[i]) * t;
  return out as unknown as Latent;
}

/** '#rrggbb' or 'rrggbb' → sRGB 0..1. Throws on malformed input. */
export function hexToRgb(hex: string): [number, number, number] {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) throw new Error(`not a #rrggbb colour: ${hex}`);
  const v = parseInt(m[1], 16);
  return [((v >> 16) & 255) / 255, ((v >> 8) & 255) / 255, (v & 255) / 255];
}

/** sRGB 0..1 → '#rrggbb'. */
export function rgbToHex(rgb: ArrayLike<number>): string {
  const h = (x: number): string => Math.round(clamp01(x) * 255).toString(16).padStart(2, '0');
  return `#${h(rgb[0])}${h(rgb[1])}${h(rgb[2])}`;
}

// --- runtime rgb → latent via the official library ---------------------------

interface MixboxModule {
  floatRgbToLatent(r: number, g: number, b: number): number[] | undefined;
  latentToFloatRgb(latent: number[]): number[] | undefined;
  LATENT_SIZE: number;
}

declare global {
  interface Window {
    mixbox?: MixboxModule;
  }
}

let mixboxLoad: Promise<MixboxModule> | undefined;

/**
 * Load web/vendor/mixbox/mixbox.js on demand (once). The file is a UMD
 * bundle: loaded as a classic script it registers `window.mixbox`. Vite
 * resolves the `?url` import to the served/bundled asset path.
 */
export function loadMixbox(): Promise<MixboxModule> {
  if (!mixboxLoad) {
    mixboxLoad = (async () => {
      if (typeof window === 'undefined' || typeof document === 'undefined') {
        throw new Error('mixbox.js can only be loaded in a browser');
      }
      if (window.mixbox && typeof window.mixbox.floatRgbToLatent === 'function') return window.mixbox;
      const { default: url } = await import('../../web/vendor/mixbox/mixbox.js?url');
      await new Promise<void>((resolve, reject) => {
        const s = document.createElement('script');
        s.src = url;
        s.async = true;
        s.onload = () => resolve();
        s.onerror = () => reject(new Error(`failed to load mixbox.js from ${url}`));
        document.head.appendChild(s);
      });
      const mb = window.mixbox;
      if (!mb || typeof mb.floatRgbToLatent !== 'function') throw new Error('mixbox.js loaded but window.mixbox is missing');
      return mb;
    })();
    // let a failed load be retried on the next call
    mixboxLoad.catch(() => { mixboxLoad = undefined; });
  }
  return mixboxLoad;
}

/**
 * Convert an sRGB colour (0..1 floats, or a '#rrggbb' string) to a Mixbox
 * latent using the official library. Used by the custom colour swatch; the
 * library is fetched on first use.
 */
export async function rgbToLatentAsync(rgb: readonly [number, number, number] | string): Promise<Latent> {
  const c = typeof rgb === 'string' ? hexToRgb(rgb) : rgb;
  const mb = await loadMixbox();
  const z = mb.floatRgbToLatent(clamp01(c[0]), clamp01(c[1]), clamp01(c[2]));
  if (!z || z.length !== 7) throw new Error('mixbox.floatRgbToLatent returned no latent');
  return [z[0], z[1], z[2], z[3], z[4], z[5], z[6]];
}
