/*
 * ColorMill v2 - CPU reference MLS-MPM two-roll mill (see millref.h).
 * C99 + optional OpenMP.  All state is f32 to mirror the GPU.
 */
#include "millref.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#ifdef _OPENMP
#include <omp.h>
#endif

/* ------------------------------------------------------------------------ */
/* Mixbox (port of src/sim/mixbox.c; latents generated by the official lib)  */

const float MILLREF_LAT_WHITE[MILLREF_LATENT] = {
    0.00000000f, 0.00000000f, 0.00000000f, 1.00000000f, 0.00481862f, 0.00021851f, 0.00295198f
};
const float MILLREF_LAT_RED[MILLREF_LATENT] = {
    0.00000000f, 0.33960806f, 0.65860828f, 0.00178365f, 0.08873356f, -0.01747544f, -0.06755477f
};
const float MILLREF_LAT_BLUE[MILLREF_LATENT] = {
    0.86413725f, 0.00441961f, 0.02987264f, 0.10157050f, -0.05379499f, -0.01226009f, 0.00350272f
};
const float MILLREF_LAT_YELLOW[MILLREF_LATENT] = {
    0.00392157f, 0.85950980f, 0.00000000f, 0.13656863f, 0.03300247f, 0.10249173f, -0.08066935f
};

static float Clamp01(float x) { return x < 0.f ? 0.f : (x > 1.f ? 1.f : x); }

static void EvalPolynomial(float c0, float c1, float c2, float c3, float *r, float *g, float *b) {
    const float c00 = c0 * c0, c11 = c1 * c1, c22 = c2 * c2, c33 = c3 * c3;
    const float c01 = c0 * c1, c02 = c0 * c2, c12 = c1 * c2;
    float R = 0.f, G = 0.f, B = 0.f, w;
    w = c0 * c00; R += +0.07717053f * w; G += +0.02826978f * w; B += +0.24832992f * w;
    w = c1 * c11; R += +0.95912302f * w; G += +0.80256528f * w; B += +0.03561839f * w;
    w = c2 * c22; R += +0.74683774f * w; G += +0.04868586f * w; B += +0.00000000f * w;
    w = c3 * c33; R += +0.99518138f * w; G += +0.99978149f * w; B += +0.99704802f * w;
    w = c00 * c1; R += +0.04819146f * w; G += +0.83363781f * w; B += +0.32515377f * w;
    w = c01 * c1; R += -0.68146950f * w; G += +1.46107803f * w; B += +1.06980936f * w;
    w = c00 * c2; R += +0.27058419f * w; G += -0.15324870f * w; B += +1.98735057f * w;
    w = c02 * c2; R += +0.80478189f * w; G += +0.67093710f * w; B += +0.18424500f * w;
    w = c00 * c3; R += -0.35031003f * w; G += +1.37855826f * w; B += +3.68865000f * w;
    w = c0 * c33; R += +1.05128046f * w; G += +1.97815239f * w; B += +2.82989073f * w;
    w = c11 * c2; R += +3.21607125f * w; G += +0.81270228f * w; B += +1.03384539f * w;
    w = c1 * c22; R += +2.78893374f * w; G += +0.41565549f * w; B += -0.04487295f * w;
    w = c11 * c3; R += +3.02162577f * w; G += +2.55374103f * w; B += +0.32766114f * w;
    w = c1 * c33; R += +2.95124691f * w; G += +2.81201112f * w; B += +1.17578442f * w;
    w = c22 * c3; R += +2.82677043f * w; G += +0.79933038f * w; B += +1.81715262f * w;
    w = c2 * c33; R += +2.99691099f * w; G += +1.22593053f * w; B += +1.80653661f * w;
    w = c01 * c2; R += +1.87394106f * w; G += +2.05027182f * w; B += -0.29835996f * w;
    w = c01 * c3; R += +2.56609566f * w; G += +7.03428198f * w; B += +0.62575374f * w;
    w = c02 * c3; R += +4.08329484f * w; G += -1.40408358f * w; B += +2.14995522f * w;
    w = c12 * c3; R += +6.00078678f * w; G += +2.55552042f * w; B += +1.90739502f * w;
    *r = R; *g = G; *b = B;
}

void MillRef_LatentToRgb(const float z[MILLREF_LATENT], float rgb[3]) {
    float r, g, b;
    EvalPolynomial(z[0], z[1], z[2], z[3], &r, &g, &b);
    rgb[0] = Clamp01(r + z[4]);
    rgb[1] = Clamp01(g + z[5]);
    rgb[2] = Clamp01(b + z[6]);
}

/* ------------------------------------------------------------------------ */
/* small linear algebra (row-major 3x3)                                      */

static void Mat3Mul(const float a[9], const float b[9], float out[9]) {
    float t[9];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            t[i * 3 + j] = a[i * 3 + 0] * b[0 * 3 + j] + a[i * 3 + 1] * b[1 * 3 + j] + a[i * 3 + 2] * b[2 * 3 + j];
    memcpy(out, t, sizeof t);
}

static void Mat3MulT(const float a[9], const float b[9], float out[9]) { /* a * b^T */
    float t[9];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            t[i * 3 + j] = a[i * 3 + 0] * b[j * 3 + 0] + a[i * 3 + 1] * b[j * 3 + 1] + a[i * 3 + 2] * b[j * 3 + 2];
    memcpy(out, t, sizeof t);
}

static float Mat3Det(const float m[9]) {
    return m[0] * (m[4] * m[8] - m[5] * m[7]) - m[1] * (m[3] * m[8] - m[5] * m[6]) + m[2] * (m[3] * m[7] - m[4] * m[6]);
}

static void Cross3(const float a[3], const float b[3], float o[3]) {
    o[0] = a[1] * b[2] - a[2] * b[1];
    o[1] = a[2] * b[0] - a[0] * b[2];
    o[2] = a[0] * b[1] - a[1] * b[0];
}

/* Jacobi eigen-decomposition of F^T F -> V, sigma^2; U = F V / sigma. */
void MillRef_Svd3(const float F[9], float U[9], float S[3], float V[9]) {
    float A[9];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            A[i * 3 + j] = F[0 * 3 + i] * F[0 * 3 + j] + F[1 * 3 + i] * F[1 * 3 + j] + F[2 * 3 + i] * F[2 * 3 + j];
    float Vm[9] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
    static const int pairs[3][2] = {{0, 1}, {0, 2}, {1, 2}};
    for (int sweep = 0; sweep < 8; sweep++) {
        const float off = fabsf(A[1]) + fabsf(A[2]) + fabsf(A[5]);
        if (off < 1e-12f) break;
        for (int pi = 0; pi < 3; pi++) {
            const int p = pairs[pi][0], q = pairs[pi][1];
            const float apq = A[p * 3 + q];
            if (fabsf(apq) < 1e-20f) continue;
            const float theta = (A[q * 3 + q] - A[p * 3 + p]) / (2.f * apq);
            const float t = (theta >= 0.f ? 1.f : -1.f) / (fabsf(theta) + sqrtf(theta * theta + 1.f));
            const float c = 1.f / sqrtf(t * t + 1.f), s = t * c;
            for (int k = 0; k < 3; k++) {            /* A = A P */
                const float akp = A[k * 3 + p], akq = A[k * 3 + q];
                A[k * 3 + p] = c * akp - s * akq;
                A[k * 3 + q] = s * akp + c * akq;
            }
            for (int k = 0; k < 3; k++) {            /* A = P^T A */
                const float apk = A[p * 3 + k], aqk = A[q * 3 + k];
                A[p * 3 + k] = c * apk - s * aqk;
                A[q * 3 + k] = s * apk + c * aqk;
            }
            for (int k = 0; k < 3; k++) {            /* V = V P */
                const float vkp = Vm[k * 3 + p], vkq = Vm[k * 3 + q];
                Vm[k * 3 + p] = c * vkp - s * vkq;
                Vm[k * 3 + q] = s * vkp + c * vkq;
            }
        }
    }
    float ev[3] = {A[0], A[4], A[8]};
    int order[3] = {0, 1, 2};
    for (int i = 0; i < 2; i++)                      /* sort descending */
        for (int j = i + 1; j < 3; j++)
            if (ev[order[j]] > ev[order[i]]) { const int t = order[i]; order[i] = order[j]; order[j] = t; }
    for (int i = 0; i < 3; i++) {
        S[i] = sqrtf(ev[order[i]] > 0.f ? ev[order[i]] : 0.f);
        for (int k = 0; k < 3; k++) V[k * 3 + i] = Vm[k * 3 + order[i]];
    }
    /* keep V a proper rotation (the sort may have swapped two columns) */
    if (Mat3Det(V) < 0.f) for (int k = 0; k < 3; k++) V[k * 3 + 2] = -V[k * 3 + 2];
    /* U columns: u0 = F v0 / s0, u1 = F v1 / s1 orthogonalised against u0, u2 = u0 x u1
       (robust when a singular value is tiny; exact otherwise).  U is then a proper
       rotation and an inverted F shows up as a negative S[2]. */
    float ucol[3][3], fv2[3];
    const float eps = 1e-6f;
    for (int i = 0; i < 3; i++)
        for (int k = 0; k < 3; k++) {
            const float f = F[k * 3 + 0] * V[0 * 3 + i] + F[k * 3 + 1] * V[1 * 3 + i] + F[k * 3 + 2] * V[2 * 3 + i];
            if (i < 2) ucol[i][k] = f; else fv2[k] = f;
        }
    float l0 = sqrtf(ucol[0][0] * ucol[0][0] + ucol[0][1] * ucol[0][1] + ucol[0][2] * ucol[0][2]);
    if (l0 < eps) { ucol[0][0] = 1.f; ucol[0][1] = 0.f; ucol[0][2] = 0.f; l0 = 1.f; }
    for (int k = 0; k < 3; k++) ucol[0][k] /= l0;
    {
        const float d = ucol[1][0] * ucol[0][0] + ucol[1][1] * ucol[0][1] + ucol[1][2] * ucol[0][2];
        for (int k = 0; k < 3; k++) ucol[1][k] -= d * ucol[0][k];
        float l1 = sqrtf(ucol[1][0] * ucol[1][0] + ucol[1][1] * ucol[1][1] + ucol[1][2] * ucol[1][2]);
        if (l1 < eps) {
            float a[3] = {1, 0, 0};
            if (fabsf(ucol[0][0]) > 0.9f) { a[0] = 0; a[1] = 1; }
            Cross3(ucol[0], a, ucol[1]);
            l1 = sqrtf(ucol[1][0] * ucol[1][0] + ucol[1][1] * ucol[1][1] + ucol[1][2] * ucol[1][2]);
        }
        for (int k = 0; k < 3; k++) ucol[1][k] /= l1;
    }
    Cross3(ucol[0], ucol[1], ucol[2]);
    if (fv2[0] * ucol[2][0] + fv2[1] * ucol[2][1] + fv2[2] * ucol[2][2] < 0.f) S[2] = -S[2];
    for (int i = 0; i < 3; i++) for (int k = 0; k < 3; k++) U[k * 3 + i] = ucol[i][k];
}

/* ------------------------------------------------------------------------ */

struct MillRefSim {
    MillRefOptions opt;
    MillRefMaterial mat;
    MillRefParams par;
    float h, invH;
    int nx, ny, nz, nodeCount;
    float domain[3];
    float mu, lambda;
    float pMass, pVol, forceVol;
    float tackBand;                                  /* absolute */
    float backAxisZ, frontAxisZ, omegaBack, omegaFront;
    MillRefParticle *p;
    int n;
    float *gm, *gv;                                  /* node mass, momentum -> velocity (3*nodeCount) */
    float *tm, *tv;                                  /* per-thread accumulators */
    int nthreads;
    float *pm, *plat;                                /* pigment raster */
    double time;
    int frame;
    long pushOuts;
    double frameMs, p2gMs, gridMs, g2pMs;
};

MillRefOptions MillRef_DefaultOptions(void) {
    MillRefOptions o;
    o.cells = 32; o.dt = 1.6e-3f; o.sub = 8;
    o.tackBand = 1.5f; o.tackBlend = 1.f;
    o.rho = 0.f;                                     /* literal spec */
    o.floorFriction = 0.6f; o.damping = 0.f;
    o.fixedPoint = 0; o.threads = 0; o.seed = 1234u;
    o.bankHeight = MILLREF_BANK_HEIGHT; o.bankHalfDepth = MILLREF_BANK_HALF_DEPTH;
    o.plastic = 0; o.yieldStrain = 0.02f; o.jMin = 0.f; o.jMax = 0.f;
    return o;
}

MillRefMaterial MillRef_DefaultMaterial(void) {
    MillRefMaterial m = {60.f, 0.35f, 0.025f, 0.0075f};
    return m;
}

MillRefParams MillRef_DefaultParams(void) {
    MillRefParams p = {3.f, 1.25f, 0.05f, 2.f, 0.6f, 0.4f};
    return p;
}

static double NowMs(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000.0 + ts.tv_nsec * 1e-6;
}

static void UpdateRollers(MillRefSim *sim) {
    const float half = MILLREF_RADIUS + sim->par.gap * 0.5f;
    sim->backAxisZ = MILLREF_NIP_Z - half;
    sim->frontAxisZ = MILLREF_NIP_Z + half;
    sim->omegaBack = +sim->par.omega * sim->par.frictionRatio;
    sim->omegaFront = -sim->par.omega;
}

void MillRef_SetParams(MillRefSim *sim, const MillRefParams *par) {
    sim->par = *par;
    UpdateRollers(sim);
}

/* --- seeding: mirror of seedBankPositions() in src/config/mill.ts ---------- */

static float MillTopSurfaceY(const MillRefSim *sim, float z) {
    const float R = MILLREF_RADIUS;
    float y = MILLREF_AXIS_Y;
    const float az[2] = {sim->backAxisZ, sim->frontAxisZ};
    for (int r = 0; r < 2; r++) {
        const float dz = z - az[r];
        if (fabsf(dz) < R) {
            const float yy = MILLREF_AXIS_Y + sqrtf(R * R - dz * dz);
            if (yy > y) y = yy;
        }
    }
    return y;
}

static float Xorshift(unsigned *s) {
    unsigned x = *s;
    x ^= x << 13; x ^= x >> 17; x ^= x << 5;
    *s = x;
    return (float)((double)x / 4294967296.0);
}

static void Raster(MillRefSim *sim);

static void Seed(MillRefSim *sim) {
    const float h = sim->h;
    const int per = MILLREF_SEED_PER_AXIS;
    const float bx0 = MILLREF_BANK_END_MARGIN, bx1 = MILLREF_LENGTH - MILLREF_BANK_END_MARGIN;
    const float by0 = MILLREF_AXIS_Y, by1 = MILLREF_AXIS_Y + MILLREF_RADIUS + sim->opt.bankHeight;
    const float bz0 = MILLREF_NIP_Z - sim->opt.bankHalfDepth, bz1 = MILLREF_NIP_Z + sim->opt.bankHalfDepth;
    const float R = MILLREF_RADIUS;
    unsigned s = sim->opt.seed;
    const int cx0 = (int)floorf(bx0 / h), cx1 = (int)ceilf(bx1 / h);
    const int cy0 = (int)floorf(by0 / h), cy1 = (int)ceilf(by1 / h);
    const int cz0 = (int)floorf(bz0 / h), cz1 = (int)ceilf(bz1 / h);
    const float jitter = 0.35f;
    int cap = (cx1 - cx0) * (cy1 - cy0) * (cz1 - cz0) * per * per * per;
    sim->p = (MillRefParticle *)calloc((size_t)cap, sizeof(MillRefParticle));
    int n = 0;
    for (int cz = cz0; cz < cz1; cz++)
        for (int cy = cy0; cy < cy1; cy++)
            for (int cx = cx0; cx < cx1; cx++)
                for (int sz = 0; sz < per; sz++)
                    for (int sy = 0; sy < per; sy++)
                        for (int sx = 0; sx < per; sx++) {
                            const float x = (cx + (sx + 0.5f + (Xorshift(&s) - 0.5f) * jitter) / per) * h;
                            const float y = (cy + (sy + 0.5f + (Xorshift(&s) - 0.5f) * jitter) / per) * h;
                            const float z = (cz + (sz + 0.5f + (Xorshift(&s) - 0.5f) * jitter) / per) * h;
                            if (x < bx0 || x > bx1 || z < bz0 || z > bz1 || y > by1) continue;
                            if (y < MillTopSurfaceY(sim, z) + 0.25f * h) continue;
                            if (hypotf(y - MILLREF_AXIS_Y, z - sim->backAxisZ) < R + 0.25f * h) continue;
                            if (hypotf(y - MILLREF_AXIS_Y, z - sim->frontAxisZ) < R + 0.25f * h) continue;
                            MillRefParticle *q = &sim->p[n++];
                            q->x[0] = x; q->x[1] = y; q->x[2] = z;
                            q->v[0] = q->v[1] = q->v[2] = 0.f;
                            memset(q->C, 0, sizeof q->C);
                            memset(q->F, 0, sizeof q->F);
                            q->F[0] = q->F[4] = q->F[8] = 1.f;
                            memcpy(q->R, q->F, sizeof q->R);
                            memcpy(q->lat, MILLREF_LAT_WHITE, sizeof q->lat);
                            q->flags = 0;
                        }
    sim->n = n;
}

MillRefSim *MillRef_Create(const MillRefOptions *opt, const MillRefMaterial *mat, const MillRefParams *par) {
    MillRefSim *sim = (MillRefSim *)calloc(1, sizeof(MillRefSim));
    sim->opt = *opt; sim->mat = *mat; sim->par = *par;
    sim->h = 1.f / (float)opt->cells;
    sim->invH = (float)opt->cells;
    sim->domain[0] = MILLREF_DOMAIN_X; sim->domain[1] = MILLREF_DOMAIN_Y; sim->domain[2] = MILLREF_DOMAIN_Z;
    sim->nx = (int)lroundf(sim->domain[0] / sim->h) + 1;
    sim->ny = (int)lroundf(sim->domain[1] / sim->h) + 1;
    sim->nz = (int)lroundf(sim->domain[2] / sim->h) + 1;
    sim->nodeCount = sim->nx * sim->ny * sim->nz;
    sim->mu = mat->E / (2.f * (1.f + mat->nu));
    sim->lambda = mat->E * mat->nu / ((1.f + mat->nu) * (1.f - 2.f * mat->nu));
    sim->pMass = 1.f;
    sim->pVol = sim->h * sim->h * sim->h / 8.f;
    const float rhoSpec = 8.f / (sim->h * sim->h * sim->h);
    sim->forceVol = opt->rho > 0.f ? sim->pVol * rhoSpec / opt->rho : sim->pVol;
    sim->tackBand = opt->tackBand * sim->h;
    UpdateRollers(sim);
    Seed(sim);

#ifdef _OPENMP
    if (opt->threads > 0) omp_set_num_threads(opt->threads);
    sim->nthreads = omp_get_max_threads();
#else
    sim->nthreads = 1;
#endif
    sim->gm = (float *)calloc((size_t)sim->nodeCount, sizeof(float));
    sim->gv = (float *)calloc((size_t)sim->nodeCount * 3, sizeof(float));
    sim->tm = (float *)calloc((size_t)sim->nodeCount * sim->nthreads, sizeof(float));
    sim->tv = (float *)calloc((size_t)sim->nodeCount * 3 * sim->nthreads, sizeof(float));
    sim->pm = (float *)calloc((size_t)sim->nodeCount, sizeof(float));
    sim->plat = (float *)calloc((size_t)sim->nodeCount * MILLREF_LATENT, sizeof(float));
    Raster(sim);                                     /* so frame-0 stats have a density field */
    return sim;
}

void MillRef_Destroy(MillRefSim *sim) {
    if (!sim) return;
    free(sim->p); free(sim->gm); free(sim->gv); free(sim->tm); free(sim->tv); free(sim->pm); free(sim->plat);
    free(sim);
}

/* ------------------------------------------------------------------------ */

static void QuadWeights(float fx, float w[3]) {
    const float a = 1.5f - fx, b = fx - 1.f, c = fx - 0.5f;
    w[0] = 0.5f * a * a;
    w[1] = 0.75f - b * b;
    w[2] = 0.5f * c * c;
}

static int NodeIndex(const MillRefSim *sim, int i, int j, int k) {
    return (k * sim->ny + j) * sim->nx + i;
}

/* Cauchy stress of the fixed corotated model (design section 4), row-major */
static void Stress(const MillRefSim *sim, const MillRefParticle *p, float sigma[9]) {
    float FmR[9], PFt[9];
    for (int i = 0; i < 9; i++) FmR[i] = p->F[i] - p->R[i];
    Mat3MulT(FmR, p->F, PFt);                        /* (F - R) F^T */
    const float J = Mat3Det(p->F);
    const float invJ = 1.f / J;
    const float vol = sim->lambda * J * (J - 1.f);
    for (int i = 0; i < 9; i++) sigma[i] = 2.f * sim->mu * PFt[i] * invJ;
    sigma[0] += vol * invJ; sigma[4] += vol * invJ; sigma[8] += vol * invJ;
}

static void P2G(MillRefSim *sim) {
    const float h = sim->h, invH = sim->invH, dt = sim->opt.dt;
    const float pMass = sim->pMass;
    const float stressScale = -dt * sim->forceVol * 4.f * invH * invH;
    const int nc = sim->nodeCount, nt = sim->nthreads;
    memset(sim->tm, 0, sizeof(float) * (size_t)nc * nt);
    memset(sim->tv, 0, sizeof(float) * (size_t)nc * 3 * nt);
#pragma omp parallel
    {
#ifdef _OPENMP
        const int tid = omp_get_thread_num();
#else
        const int tid = 0;
#endif
        float *tm = sim->tm + (size_t)tid * nc;
        float *tv = sim->tv + (size_t)tid * nc * 3;
#pragma omp for schedule(static)
        for (int pi = 0; pi < sim->n; pi++) {
            const MillRefParticle *p = &sim->p[pi];
            if (p->flags & 1u) continue;
            const float gx = p->x[0] * invH, gy = p->x[1] * invH, gz = p->x[2] * invH;
            const int bx = (int)floorf(gx - 0.5f), by = (int)floorf(gy - 0.5f), bz = (int)floorf(gz - 0.5f);
            const float fx = gx - (float)bx, fy = gy - (float)by, fz = gz - (float)bz;
            float wx[3], wy[3], wz[3];
            QuadWeights(fx, wx); QuadWeights(fy, wy); QuadWeights(fz, wz);
            float sigma[9], aff[9];
            Stress(sim, p, sigma);
            for (int i = 0; i < 9; i++) aff[i] = stressScale * sigma[i] + pMass * p->C[i];
            const float mv0 = pMass * p->v[0], mv1 = pMass * p->v[1], mv2 = pMass * p->v[2];
            for (int i = 0; i < 3; i++) {
                const float dpx = ((float)i - fx) * h;
                for (int j = 0; j < 3; j++) {
                    const float dpy = ((float)j - fy) * h;
                    const float wxy = wx[i] * wy[j];
                    for (int k = 0; k < 3; k++) {
                        const float dpz = ((float)k - fz) * h;
                        const float w = wxy * wz[k];
                        const int n = NodeIndex(sim, bx + i, by + j, bz + k);
                        tm[n] += w * pMass;
                        tv[n * 3 + 0] += w * (mv0 + aff[0] * dpx + aff[1] * dpy + aff[2] * dpz);
                        tv[n * 3 + 1] += w * (mv1 + aff[3] * dpx + aff[4] * dpy + aff[5] * dpz);
                        tv[n * 3 + 2] += w * (mv2 + aff[6] * dpx + aff[7] * dpy + aff[8] * dpz);
                    }
                }
            }
        }
    }
    /* reduce per-thread grids (fixed order -> deterministic) */
    const int fixed = sim->opt.fixedPoint;
#pragma omp parallel for schedule(static)
    for (int n = 0; n < nc; n++) {
        float m = 0.f, v0 = 0.f, v1 = 0.f, v2 = 0.f;
        for (int t = 0; t < nt; t++) {
            m += sim->tm[(size_t)t * nc + n];
            v0 += sim->tv[((size_t)t * nc + n) * 3 + 0];
            v1 += sim->tv[((size_t)t * nc + n) * 3 + 1];
            v2 += sim->tv[((size_t)t * nc + n) * 3 + 2];
        }
        if (fixed) {
            m = roundf(m * 1048576.f) / 1048576.f;
            v0 = roundf(v0 * 65536.f) / 65536.f;
            v1 = roundf(v1 * 65536.f) / 65536.f;
            v2 = roundf(v2 * 65536.f) / 65536.f;
        }
        sim->gm[n] = m;
        sim->gv[n * 3 + 0] = v0; sim->gv[n * 3 + 1] = v1; sim->gv[n * 3 + 2] = v2;
    }
}

static void GridUpdate(MillRefSim *sim) {
    const float h = sim->h, dt = sim->opt.dt;
    const float R = MILLREF_RADIUS, ay = MILLREF_AXIS_Y;
    const float fz = sim->frontAxisZ, bz = sim->backAxisZ;
    const float wf = sim->omegaFront, wb = sim->omegaBack;
    const float tack = sim->tackBand, blend = sim->opt.tackBlend;
    const float muB = sim->par.backFriction;
    const float g = sim->par.gravity;
    const float margin = 2.f * h;
    const float floorScale = 1.f - sim->opt.floorFriction > 0.f ? 1.f - sim->opt.floorFriction : 0.f;
    const float damp = 1.f - sim->opt.damping;
#pragma omp parallel for schedule(static)
    for (int n = 0; n < sim->nodeCount; n++) {
        const float m = sim->gm[n];
        if (m <= 0.f) { sim->gv[n * 3] = sim->gv[n * 3 + 1] = sim->gv[n * 3 + 2] = 0.f; continue; }
        const int i = n % sim->nx, j = (n / sim->nx) % sim->ny, k = n / (sim->nx * sim->ny);
        const float px = i * h, py = j * h, pz = k * h;
        float vx = sim->gv[n * 3] / m, vy = sim->gv[n * 3 + 1] / m, vz = sim->gv[n * 3 + 2] / m;
        vy -= dt * g;
        if (damp != 1.f) { vx *= damp; vy *= damp; vz *= damp; }

        /* 1. front roller: sticky band */
        {
            const float dy = py - ay, dz = pz - fz;
            const float d = sqrtf(dy * dy + dz * dz);
            if (d < R + tack) {
                /* vr = (0, -w*dz, w*dy) */
                const float vry = -wf * dz, vrz = wf * dy;
                if (blend >= 1.f || d < R + 0.5f * h) {
                    vx = 0.f; vy = vry; vz = vrz;
                } else {
                    vx += (0.f - vx) * blend; vy += (vry - vy) * blend; vz += (vrz - vz) * blend;
                }
            }
        }
        /* 2. back roller: separating + Coulomb */
        {
            const float dy = py - ay, dz = pz - bz;
            const float d = sqrtf(dy * dy + dz * dz);
            if (d < R + 0.5f * h && d > 1e-9f) {
                const float ny = dy / d, nz = dz / d;
                const float vry = -wb * dz, vrz = wb * dy;
                const float rx = vx, ry = vy - vry, rz = vz - vrz;
                const float vn = ry * ny + rz * nz;
                if (vn < 0.f) {
                    float tx = rx, ty = ry - vn * ny, tz = rz - vn * nz;
                    const float tl = sqrtf(tx * tx + ty * ty + tz * tz);
                    float s = tl > 1e-12f ? 1.f - muB * (-vn) / tl : 0.f;
                    if (s < 0.f) s = 0.f;
                    tx *= s; ty *= s; tz *= s;
                    vx = tx; vy = vry + ty; vz = vrz + tz;
                }
            }
        }
        /* 3. walls */
        if (px < margin && vx < 0.f) vx = 0.f;
        if (px > sim->domain[0] - margin && vx > 0.f) vx = 0.f;
        if (pz < margin && vz < 0.f) vz = 0.f;
        if (pz > sim->domain[2] - margin && vz > 0.f) vz = 0.f;
        if (py > sim->domain[1] - margin && vy > 0.f) vy = 0.f;
        if (py < margin && vy < 0.f) { vy = 0.f; vx *= floorScale; vz *= floorScale; }

        sim->gv[n * 3] = vx; sim->gv[n * 3 + 1] = vy; sim->gv[n * 3 + 2] = vz;
    }
}

static void G2P(MillRefSim *sim) {
    const float h = sim->h, invH = sim->invH, dt = sim->opt.dt;
    const float lo = 1.5f * h;
    const float R = MILLREF_RADIUS, ay = MILLREF_AXIS_Y;
    const float az[2] = {sim->backAxisZ, sim->frontAxisZ};
    const float sMin = 1.f - sim->mat.thetaC, sMax = 1.f + sim->mat.thetaS;
    const int plastic = sim->opt.plastic;
    const float yieldStrain = sim->opt.yieldStrain;
    const float jMin = sim->opt.jMin > 0.f ? sim->opt.jMin : sMin * sMin * sMin;
    const float jMax = sim->opt.jMax > 0.f ? sim->opt.jMax : sMax * sMax * sMax;
    long pushOuts = 0;
#pragma omp parallel for schedule(static) reduction(+ : pushOuts)
    for (int pi = 0; pi < sim->n; pi++) {
        MillRefParticle *p = &sim->p[pi];
        if (p->flags & 1u) continue;
        const float gx = p->x[0] * invH, gy = p->x[1] * invH, gz = p->x[2] * invH;
        const int bx = (int)floorf(gx - 0.5f), by = (int)floorf(gy - 0.5f), bz = (int)floorf(gz - 0.5f);
        const float fx = gx - (float)bx, fy = gy - (float)by, fz = gz - (float)bz;
        float wx[3], wy[3], wz[3];
        QuadWeights(fx, wx); QuadWeights(fy, wy); QuadWeights(fz, wz);
        float nv[3] = {0, 0, 0}, nC[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};
        for (int i = 0; i < 3; i++) {
            const float dpx = ((float)i - fx) * h;
            for (int j = 0; j < 3; j++) {
                const float dpy = ((float)j - fy) * h;
                const float wxy = wx[i] * wy[j];
                for (int k = 0; k < 3; k++) {
                    const float dpz = ((float)k - fz) * h;
                    const float w = wxy * wz[k];
                    const int n = NodeIndex(sim, bx + i, by + j, bz + k);
                    const float v0 = sim->gv[n * 3], v1 = sim->gv[n * 3 + 1], v2 = sim->gv[n * 3 + 2];
                    nv[0] += w * v0; nv[1] += w * v1; nv[2] += w * v2;
                    const float s = 4.f * invH * invH * w;
                    nC[0] += s * v0 * dpx; nC[1] += s * v0 * dpy; nC[2] += s * v0 * dpz;
                    nC[3] += s * v1 * dpx; nC[4] += s * v1 * dpy; nC[5] += s * v1 * dpz;
                    nC[6] += s * v2 * dpx; nC[7] += s * v2 * dpy; nC[8] += s * v2 * dpz;
                }
            }
        }
        memcpy(p->v, nv, sizeof nv);
        memcpy(p->C, nC, sizeof nC);
        /* F = (I + dt C) F */
        float A[9], Fn[9];
        for (int i = 0; i < 9; i++) A[i] = dt * nC[i];
        A[0] += 1.f; A[4] += 1.f; A[8] += 1.f;
        Mat3Mul(A, p->F, Fn);
        /* plastic return */
        float U[9], S[3], V[9];
        MillRef_Svd3(Fn, U, S, V);
        if (plastic == 0) {
            for (int i = 0; i < 3; i++) S[i] = S[i] < sMin ? sMin : (S[i] > sMax ? sMax : S[i]);
        } else {
            /* von Mises return in Hencky strain: keep the volumetric part elastic (plastic 2: clamp it),
               scale the deviatoric part back onto the yield surface */
            float e[3];
            for (int i = 0; i < 3; i++) e[i] = logf(S[i] > 1e-3f ? S[i] : 1e-3f);
            float mean = (e[0] + e[1] + e[2]) / 3.f;
            float dev[3], n2 = 0.f;
            for (int i = 0; i < 3; i++) { dev[i] = e[i] - mean; n2 += dev[i] * dev[i]; }
            const float n = sqrtf(n2);
            if (n > yieldStrain) for (int i = 0; i < 3; i++) dev[i] *= yieldStrain / n;
            if (plastic == 2) {
                const float lo = logf(jMin) / 3.f, hi = logf(jMax) / 3.f;   /* mean Hencky strain = ln(J)/3 */
                mean = mean < lo ? lo : (mean > hi ? hi : mean);
            }
            for (int i = 0; i < 3; i++) S[i] = expf(mean + dev[i]);
        }
        float US[9];
        for (int r = 0; r < 3; r++) for (int c = 0; c < 3; c++) US[r * 3 + c] = U[r * 3 + c] * S[c];
        Mat3MulT(US, V, p->F);
        Mat3MulT(U, V, p->R);
        /* advect + clamp */
        for (int a = 0; a < 3; a++) {
            float xa = p->x[a] + dt * nv[a];
            const float hi = sim->domain[a] - lo;
            p->x[a] = xa < lo ? lo : (xa > hi ? hi : xa);
        }
        /* hard safety: push out of rollers */
        for (int r = 0; r < 2; r++) {
            const float dy = p->x[1] - ay, dz = p->x[2] - az[r];
            const float d = sqrtf(dy * dy + dz * dz);
            if (d < R) {
                const float t = (R + 0.25f * h) / (d > 1e-9f ? d : 1e-9f);
                p->x[1] = ay + dy * t;
                p->x[2] = az[r] + dz * t;
                pushOuts++;
            }
        }
    }
    sim->pushOuts += pushOuts;
}

void MillRef_Substep(MillRefSim *sim) {
    double t0 = NowMs();
    P2G(sim);
    double t1 = NowMs();
    GridUpdate(sim);
    double t2 = NowMs();
    G2P(sim);
    double t3 = NowMs();
    sim->p2gMs += t1 - t0; sim->gridMs += t2 - t1; sim->g2pMs += t3 - t2;
    sim->time += sim->opt.dt;
}

/* --- frame-level kernels (section 3.5 / 5) -------------------------------- */

static void Raster(MillRefSim *sim) {
    const int nc = sim->nodeCount;
    const float invH = sim->invH, pMass = sim->pMass;
    memset(sim->pm, 0, sizeof(float) * (size_t)nc);
    memset(sim->plat, 0, sizeof(float) * (size_t)nc * MILLREF_LATENT);
    /* single-threaded scatter (once per frame; cheap enough) */
    for (int pi = 0; pi < sim->n; pi++) {
        const MillRefParticle *p = &sim->p[pi];
        const float gx = p->x[0] * invH, gy = p->x[1] * invH, gz = p->x[2] * invH;
        const int bx = (int)floorf(gx - 0.5f), by = (int)floorf(gy - 0.5f), bz = (int)floorf(gz - 0.5f);
        const float fx = gx - (float)bx, fy = gy - (float)by, fz = gz - (float)bz;
        float wx[3], wy[3], wz[3];
        QuadWeights(fx, wx); QuadWeights(fy, wy); QuadWeights(fz, wz);
        for (int i = 0; i < 3; i++)
            for (int j = 0; j < 3; j++)
                for (int k = 0; k < 3; k++) {
                    const float w = wx[i] * wy[j] * wz[k] * pMass;
                    const int n = NodeIndex(sim, bx + i, by + j, bz + k);
                    sim->pm[n] += w;
                    for (int l = 0; l < MILLREF_LATENT; l++) sim->plat[n * MILLREF_LATENT + l] += w * p->lat[l];
                }
    }
}

static void Disperse(MillRefSim *sim) {
    const float invH = sim->invH;
    const float k = sim->par.dispersion;
    const float frameDt = sim->opt.dt * (float)sim->opt.sub;
#pragma omp parallel for schedule(static)
    for (int pi = 0; pi < sim->n; pi++) {
        MillRefParticle *p = &sim->p[pi];
        const float gx = p->x[0] * invH, gy = p->x[1] * invH, gz = p->x[2] * invH;
        const int bx = (int)floorf(gx - 0.5f), by = (int)floorf(gy - 0.5f), bz = (int)floorf(gz - 0.5f);
        const float fx = gx - (float)bx, fy = gy - (float)by, fz = gz - (float)bz;
        float wx[3], wy[3], wz[3];
        QuadWeights(fx, wx); QuadWeights(fy, wy); QuadWeights(fz, wz);
        float zm = 0.f, zg[MILLREF_LATENT] = {0, 0, 0, 0, 0, 0, 0};
        for (int i = 0; i < 3; i++)
            for (int j = 0; j < 3; j++)
                for (int kk = 0; kk < 3; kk++) {
                    const float w = wx[i] * wy[j] * wz[kk];
                    const int n = NodeIndex(sim, bx + i, by + j, bz + kk);
                    zm += w * sim->pm[n];
                    for (int l = 0; l < MILLREF_LATENT; l++) zg[l] += w * sim->plat[n * MILLREF_LATENT + l];
                }
        if (zm <= 1e-12f) continue;
        for (int l = 0; l < MILLREF_LATENT; l++) zg[l] /= zm;
        /* shear rate = ||(C + C^T)/2||_F */
        float g2 = 0.f;
        for (int r = 0; r < 3; r++)
            for (int c = 0; c < 3; c++) {
                const float s = 0.5f * (p->C[r * 3 + c] + p->C[c * 3 + r]);
                g2 += s * s;
            }
        float a = k * sqrtf(g2) * frameDt;
        a = Clamp01(a);
        for (int l = 0; l < MILLREF_LATENT; l++) p->lat[l] += a * (zg[l] - p->lat[l]);
    }
}

void MillRef_Frame(MillRefSim *sim) {
    const double t0 = NowMs();
    sim->pushOuts = 0;
    sim->p2gMs = sim->gridMs = sim->g2pMs = 0.0;
    for (int s = 0; s < sim->opt.sub; s++) MillRef_Substep(sim);
    Raster(sim);
    Disperse(sim);
    sim->frame++;
    sim->frameMs = NowMs() - t0;
}

void MillRef_AddPigment(MillRefSim *sim, const float center[3], float radius,
                        const float latent[MILLREF_LATENT], float strength) {
    for (int pi = 0; pi < sim->n; pi++) {
        MillRefParticle *p = &sim->p[pi];
        const float dx = p->x[0] - center[0], dy = p->x[1] - center[1], dz = p->x[2] - center[2];
        const float d = sqrtf(dx * dx + dy * dy + dz * dz);
        if (d >= radius) continue;
        const float t = 1.f - d / radius;
        const float a = Clamp01(strength * t);
        for (int l = 0; l < MILLREF_LATENT; l++) p->lat[l] += a * (latent[l] - p->lat[l]);
    }
}

/* ------------------------------------------------------------------------ */

static int Finite3(const float *v, int n) {
    for (int i = 0; i < n; i++) if (!isfinite(v[i])) return 0;
    return 1;
}

void MillRef_Stats(const MillRefSim *sim, MillRefStats *st) {
    memset(st, 0, sizeof *st);
    const float h = sim->h, R = MILLREF_RADIUS, ay = MILLREF_AXIS_Y;
    const float gap = sim->par.gap;
    st->count = sim->n;
    st->minJ = 1e30f; st->maxJ = -1e30f; st->minSigma = 1e30f; st->maxSigma = -1e30f;
    st->sheetY0 = 1e30f;
    double sumV = 0.0, nipShear = 0.0;
    int sheetF = 0, sheetB = 0, bank = 0, floorN = 0, frontTop = 0, backTop = 0, inNip = 0;
    int pig = 0, pigSheet = 0, pigBank = 0, greenS = 0, greenB = 0, blueB = 0, yellowB = 0;
    int loose = 0, high = 0;
    double sheetD = 0.0;
    const float bankTop = MILLREF_AXIS_Y + MILLREF_RADIUS + sim->opt.bankHeight;
    const float invH = sim->invH;
    for (int pi = 0; pi < sim->n; pi++) {
        const MillRefParticle *p = &sim->p[pi];
        if (!Finite3(p->x, 3) || !Finite3(p->v, 3) || !Finite3(p->F, 9) || !Finite3(p->C, 9) || !Finite3(p->lat, 7)) {
            st->nan++;
            continue;
        }
        const float x = p->x[0], y = p->x[1], z = p->x[2];
        if (x >= 0.f && x <= sim->domain[0] && y >= 0.f && y <= sim->domain[1] && z >= 0.f && z <= sim->domain[2]) st->inDomain++;
        const float dF = hypotf(y - ay, z - sim->frontAxisZ), dB = hypotf(y - ay, z - sim->backAxisZ);
        if (dF < R || dB < R) st->inRoller++;
        const float vm = sqrtf(p->v[0] * p->v[0] + p->v[1] * p->v[1] + p->v[2] * p->v[2]);
        if (vm > st->maxV) st->maxV = vm;
        sumV += vm;
        const float J = Mat3Det(p->F);
        if (J < st->minJ) st->minJ = J;
        if (J > st->maxJ) st->maxJ = J;
        /* singular value bounds via F^T F trace bound is not exact; use SVD on a sample */
        if ((pi & 63) == 0) {
            float U[9], S[3], V[9];
            MillRef_Svd3(p->F, U, S, V);
            for (int i = 0; i < 3; i++) {
                if (S[i] < st->minSigma) st->minSigma = S[i];
                if (S[i] > st->maxSigma) st->maxSigma = S[i];
            }
        }
        const int onFront = dF < R + 4.f * h, onBack = dB < R + 4.f * h;
        const int sF = onFront && y < ay, sB = onBack && y < ay;
        sheetF += sF; sheetB += sB;
        if (sF && y < st->sheetY0) st->sheetY0 = y;
        if (sF) sheetD += dF - R;
        if (y >= ay) bank++;
        if (y < 3.f * h) floorN++;
        if (y > bankTop + h) high++;
        {
            /* gathered raster mass at the particle (raster is refreshed once per frame) */
            const float gx = x * invH, gy = y * invH, gz = z * invH;
            const int bx = (int)floorf(gx - 0.5f), by = (int)floorf(gy - 0.5f), bz = (int)floorf(gz - 0.5f);
            const float fx = gx - (float)bx, fy = gy - (float)by, fz = gz - (float)bz;
            float wx[3], wy[3], wz[3];
            QuadWeights(fx, wx); QuadWeights(fy, wy); QuadWeights(fz, wz);
            float m = 0.f;
            for (int i = 0; i < 3; i++)
                for (int j = 0; j < 3; j++)
                    for (int k = 0; k < 3; k++) m += wx[i] * wy[j] * wz[k] * sim->pm[NodeIndex(sim, bx + i, by + j, bz + k)];
            if (m < 2.f) loose++;
        }
        if (onFront && y >= ay) frontTop++;
        if (onBack && y >= ay) backTop++;
        const int nip = fabsf(z - MILLREF_NIP_Z) < gap * 0.5f + h && fabsf(y - ay) < 3.f * h;
        if (nip) {
            inNip++;
            float g2 = 0.f;
            for (int r = 0; r < 3; r++)
                for (int c = 0; c < 3; c++) {
                    const float s = 0.5f * (p->C[r * 3 + c] + p->C[c * 3 + r]);
                    g2 += s * s;
                }
            nipShear += sqrt((double)g2);
        }
        float dl = 0.f;
        for (int l = 0; l < MILLREF_LATENT; l++) { const float d = p->lat[l] - MILLREF_LAT_WHITE[l]; dl += d * d; }
        if (dl > 0.05f * 0.05f) {
            pig++;
            float rgb[3];
            MillRef_LatentToRgb(p->lat, rgb);
            const int green = rgb[1] > rgb[0] + 0.05f && rgb[1] > rgb[2] + 0.05f;
            const int blue = rgb[2] > rgb[0] + 0.1f && rgb[2] > rgb[1] + 0.1f;
            const int yellow = rgb[0] > rgb[2] + 0.2f && rgb[1] > rgb[2] + 0.2f && fabsf(rgb[0] - rgb[1]) < 0.25f;
            if (sF) { pigSheet++; greenS += green; }
            if (y >= ay) { pigBank++; greenB += green; blueB += blue; yellowB += yellow; }
        }
    }
    const float inv = sim->n > 0 ? 1.f / (float)sim->n : 0.f;
    st->meanV = (float)(sumV * inv);
    st->sheetFront = sheetF * inv; st->sheetBack = sheetB * inv; st->bank = bank * inv; st->floor = floorN * inv;
    st->frontTop = frontTop * inv; st->backTop = backTop * inv; st->inNip = inNip * inv;
    st->nipCount = inNip;
    st->loose = loose * inv; st->high = high * inv;
    st->sheetThick = sheetF > 0 ? (float)(2.0 * sheetD / sheetF) : 0.f;
    st->nipShear = inNip > 0 ? (float)(nipShear / inNip) : 0.f;
    st->pigmented = pig; st->pigmentedSheet = pigSheet; st->pigmentedBank = pigBank;
    st->greenSheet = pigSheet > 0 ? (float)greenS / pigSheet : 0.f;
    st->greenBank = pigBank > 0 ? (float)greenB / pigBank : 0.f;
    st->blueBank = pigBank > 0 ? (float)blueB / pigBank : 0.f;
    st->yellowBank = pigBank > 0 ? (float)yellowB / pigBank : 0.f;
    st->pushOuts = sim->pushOuts;
    float mm = 0.f;
    for (int n = 0; n < sim->nodeCount; n++) if (sim->gm[n] > mm) mm = sim->gm[n];
    st->maxNodeMass = mm;
    if (st->sheetY0 > 1e29f) st->sheetY0 = 0.f;
}

int MillRef_ParticleCount(const MillRefSim *sim) { return sim->n; }
const MillRefParticle *MillRef_Particles(const MillRefSim *sim) { return sim->p; }
float MillRef_H(const MillRefSim *sim) { return sim->h; }
double MillRef_Time(const MillRefSim *sim) { return sim->time; }
int MillRef_FrameIndex(const MillRefSim *sim) { return sim->frame; }
void MillRef_RollerAxes(const MillRefSim *sim, float *backZ, float *frontZ) { *backZ = sim->backAxisZ; *frontZ = sim->frontAxisZ; }
void MillRef_Timings(const MillRefSim *sim, double *frameMs, double *p2gMs, double *gridMs, double *g2pMs) {
    *frameMs = sim->frameMs; *p2gMs = sim->p2gMs; *gridMs = sim->gridMs; *g2pMs = sim->g2pMs;
}
